export const mockLessons = [
  {
    id: "L01",
    title: "Khái niệm đạo hàm",
    subject: "Toán",
    grade: "Lớp 12",
    topicName: "Đạo hàm",
  },
  {
    id: "L02",
    title: "Cực trị của hàm số",
    subject: "Toán",
    grade: "Lớp 12",
    topicName: "Cực trị",
  },
  {
    id: "L03",
    title: "Dao động điều hòa",
    subject: "Vật Lý",
    grade: "Lớp 11",
    topicName: "Dao động điều hòa",
  },
  {
    id: "L04",
    title: "Cấu trúc DNA",
    subject: "Sinh học",
    grade: "Lớp 12",
    topicName: "DNA",
  },
  {
    id: "L05",
    title: "Phản ứng oxi hóa khử",
    subject: "Hóa Học",
    grade: "Lớp 10",
    topicName: "Oxi hóa khử",
  },
];

export const initialExercises = [
  {
    id: "EX01",
    title: "Luyện tập đạo hàm cơ bản",
    lessonId: "L01",
    lessonTitle: "Khái niệm đạo hàm",
    subject: "Toán",
    grade: "Lớp 12",
    questionCount: 8,
    duration: 12,
    passScore: 70,
    status: "Đã xuất bản",
    updatedAt: "2026-05-02",
  },
  {
    id: "EX02",
    title: "Nhận biết cực trị hàm số",
    lessonId: "L02",
    lessonTitle: "Cực trị của hàm số",
    subject: "Toán",
    grade: "Lớp 12",
    questionCount: 10,
    duration: 15,
    passScore: 75,
    status: "Bản nháp",
    updatedAt: "2026-05-05",
  },
  {
    id: "EX03",
    title: "Trắc nghiệm dao động điều hòa",
    lessonId: "L03",
    lessonTitle: "Dao động điều hòa",
    subject: "Vật Lý",
    grade: "Lớp 11",
    questionCount: 6,
    duration: 10,
    passScore: 70,
    status: "Đang ẩn",
    updatedAt: "2026-05-06",
  },
  {
    id: "EX04",
    title: "Củng cố cấu trúc DNA",
    lessonId: "L04",
    lessonTitle: "Cấu trúc DNA",
    subject: "Sinh học",
    grade: "Lớp 12",
    questionCount: 12,
    duration: 18,
    passScore: 80,
    status: "Đã xuất bản",
    updatedAt: "2026-05-08",
  },
  {
    id: "EX05",
    title: "Phân loại phản ứng oxi hóa khử",
    lessonId: "L05",
    lessonTitle: "Phản ứng oxi hóa khử",
    subject: "Hóa Học",
    grade: "Lớp 10",
    questionCount: 9,
    duration: 14,
    passScore: 70,
    status: "Đã xuất bản",
    updatedAt: "2026-05-10",
  },
];

export const mockQuestionBank = [
  {
    id: "Q01",
    content: "Đạo hàm của hàm số y = x^2 là gì?",
    subject: "Toán",
    grade: "Lớp 12",
    topicName: "Đạo hàm",
    level: "Dễ",
    options: [
      { content: "2x", isCorrect: true },
      { content: "x", isCorrect: false },
      { content: "2", isCorrect: false },
      { content: "x^3", isCorrect: false },
    ],
  },
  {
    id: "Q02",
    content: "Điều kiện để hàm bậc ba có hai điểm cực trị là gì?",
    subject: "Toán",
    grade: "Lớp 12",
    topicName: "Cực trị",
    level: "Trung bình",
    options: [
      { content: "Phương trình y' = 0 có hai nghiệm phân biệt", isCorrect: true },
      { content: "Phương trình y' = 0 vô nghiệm", isCorrect: false },
      { content: "Hệ số b bằng 0", isCorrect: false },
      { content: "Hàm số luôn đồng biến", isCorrect: false },
    ],
  },
  {
    id: "Q03",
    content: "Trong dao động điều hòa, đại lượng nào không đổi theo thời gian?",
    subject: "Vật Lý",
    grade: "Lớp 11",
    topicName: "Dao động điều hòa",
    level: "Dễ",
    options: [
      { content: "Cơ năng", isCorrect: true },
      { content: "Li độ", isCorrect: false },
      { content: "Vận tốc", isCorrect: false },
      { content: "Gia tốc", isCorrect: false },
    ],
  },
  {
    id: "Q04",
    content: "Phân tử DNA được cấu tạo từ các đơn phân nào?",
    subject: "Sinh học",
    grade: "Lớp 12",
    topicName: "DNA",
    level: "Dễ",
    options: [
      { content: "Nucleotide", isCorrect: true },
      { content: "Amino acid", isCorrect: false },
      { content: "Glucose", isCorrect: false },
      { content: "Acid béo", isCorrect: false },
    ],
  },
  {
    id: "Q05",
    content: "Chất khử là chất như thế nào trong phản ứng oxi hóa khử?",
    subject: "Hóa Học",
    grade: "Lớp 10",
    topicName: "Oxi hóa khử",
    level: "Trung bình",
    options: [
      { content: "Nhường electron", isCorrect: true },
      { content: "Nhận electron", isCorrect: false },
      { content: "Không đổi số oxi hóa", isCorrect: false },
      { content: "Luôn là kim loại", isCorrect: false },
    ],
  },
  {
    id: "Q06",
    content: "Tính đạo hàm của hàm số y = (2x - 1)/(x + 3).",
    subject: "Toán",
    grade: "Lớp 12",
    topicName: "Đạo hàm",
    level: "Khó",
    options: [
      { content: "7/(x + 3)^2", isCorrect: true },
      { content: "5/(x + 3)^2", isCorrect: false },
      { content: "2/(x + 3)", isCorrect: false },
      { content: "-7/(x + 3)^2", isCorrect: false },
    ],
  },
  {
    id: "Q07",
    content: "Một vật dao động điều hòa có pha ban đầu ảnh hưởng trực tiếp đến đại lượng nào?",
    subject: "Vật Lý",
    grade: "Lớp 11",
    topicName: "Dao động điều hòa",
    level: "Trung bình",
    options: [
      { content: "Trạng thái ban đầu của dao động", isCorrect: true },
      { content: "Tần số góc", isCorrect: false },
      { content: "Chu kỳ dao động", isCorrect: false },
      { content: "Cơ năng toàn phần", isCorrect: false },
    ],
  },
  {
    id: "Q08",
    content: "Trong cơ chế nhân đôi DNA, enzyme nào có vai trò tháo xoắn phân tử DNA?",
    subject: "Sinh học",
    grade: "Lớp 12",
    topicName: "DNA",
    level: "Khó",
    options: [
      { content: "Helicase", isCorrect: true },
      { content: "Ligase", isCorrect: false },
      { content: "DNA polymerase", isCorrect: false },
      { content: "RNA polymerase", isCorrect: false },
    ],
  },
];
